version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: location_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: location_webserver
        restart: unless-stopped
        ports:
            - "8083:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: location_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    npm_network:
        external: true
    laravel:
        driver: bridge

volumes:
    dbdata:
